### ISSUE TITLE
Snippet for zebra stripes not working properly anymore after update

### ISSUE THREAD

**Issue by BobWs** [trey-wallis/obsidian-dataloom#683]
### Describe the bug

Hi,
After updating the plugin my snippet for the table zebra stripes doesn't work anymore.
This was the code before updating the plugin which was working!:
```
.theme-light .DataLoom__app tr:nth-child(odd) {
  background-color: var(--background-primary) !important;
}
.theme-light .DataLoom__app tr:nth-child(even) {
  background-color: var(--background-secondary) !important;
}
```
This is what I have tried, but then I get the column variation instead of row zebra stripes (see screenshot)
```
.theme-light .dataloom-cell--body:nth-child(odd) {
  background-color: var(--background-primary) !important;
}
.theme-light .dataloom-cell--body:nth-child(even) {
  background-color: var(--background-secondary) !important;
```
![Screen_Shot](https://github.com/trey-wallis/obsidian-dataloom/assets/5485820/97297485-11df-4b70-977a-428fa9834a9f)

Any suggestions How to change the snippet code so I get my Zebra Stripes back?
Just a though maybe you could add this as a default option to the plugin?!
TIA  
   

### Steps to reproduce

See above

### Expected behavior

I expect my Zebra Stripes to work properly again even after a update of the plugin. 

### Are you using the mobile app?

Yes

### Obsidian debug info

-

### Relevant log output

```shell
-
```

**Comment by trey-wallis** [comment]
You will need to select the rows first and then perform the even, odd operation on the individual cells within a row.

Yes, that would be something that could be added to the plugin CSS by default :)

**Comment by BobWs** [comment]
> You will need to select the rows first and then perform the even, odd operation on the individual cells within a row.

Okay, but why this change? Before I could do this for all the tables, and as I understand what you are saying I have to do this for every table I created before, sounds like a lot of extra work.
Changing the css snippet for the whole plug-in was just fine in the previous version!

**Comment by trey-wallis** [comment]
No, you don't need to do it for each table. I think there is a misunderstanding. I am saying that for the CSS selectors you will need to select the row first and then each cell within that row.

Here is a working example
```css
.theme-light .dataloom-row:nth-child(odd) .dataloom-cell--body {
    background-color: var(--background-primary) !important;
}

.theme-light .dataloom-row:nth-child(even) .dataloom-cell--body {
    background-color: var(--background-secondary) !important;
}
```
